import assert from "node:assert/strict";
import test from "node:test";
import { getSessionAdapter } from "../packages/core/src/index.mjs";
import { buildHandoff, deriveState } from "../packages/core/src/runtime/handoff.mjs";
import { buildProjection, projectionItems } from "../packages/core/src/runtime/projection.mjs";
import { sessionSnippet } from "../packages/core/src/runtime/session-title.mjs";
import { transcriptTurns } from "../packages/core/src/runtime/transcript.mjs";

// The semantic transcription contract, on fixtures shaped like the records a
// real Claude Code session writes: what the user typed, what the CLI wrote for
// itself, and what the tool machinery filed under the user's role. The
// conversation view must hold only the first of those — everything else is
// transport the user never said.

const AT = (seconds) => new Date(Date.UTC(2026, 8, 23, 9, 0, seconds)).toISOString();

function claudeLine(index, record) {
  return JSON.stringify({
    sessionId: "claude-semantics",
    uuid: `uuid-${index}`,
    timestamp: AT(index),
    cwd: "C:\\fixture\\project",
    parentUuid: index === 0 ? null : `uuid-${index - 1}`,
    ...record,
  });
}

// What a real transcript holds around the user's real words.
const CAVEAT = {
  type: "user",
  isMeta: true,
  message: {
    role: "user",
    content: "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>",
  },
};
const CLEAR_WRAPPER = {
  type: "user",
  message: {
    role: "user",
    content: "<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>",
  },
};
const GOAL = {
  type: "user",
  message: { role: "user", content: "/goal 将 Avenic 的会话系统最终收敛为真正可靠、实时、无感的多 Agent 会话体验" },
};
const THINKING_ONLY = {
  type: "assistant",
  message: {
    role: "assistant",
    model: "claude-test",
    content: [{ type: "thinking", thinking: "The user wants a long goal handled; I should start.", signature: "sig" }],
  },
};
const TOOL_CALL = {
  type: "assistant",
  message: {
    role: "assistant",
    model: "claude-test",
    content: [{ type: "tool_use", id: "toolu_1", name: "Read", input: { file_path: "src/session.mjs" } }],
  },
};
const TOOL_RESULT = {
  type: "user",
  toolUseResult: { file: "src/session.mjs" },
  message: {
    role: "user",
    content: [{ type: "tool_result", tool_use_id: "toolu_1", content: "export function session() {}" }],
  },
};
const ANSWER = {
  type: "assistant",
  message: {
    role: "assistant",
    model: "claude-test",
    content: [{ type: "text", text: "I'll start by reading the session module." }],
  },
};

const TRANSCRIPT = [
  claudeLine(0, CAVEAT),
  claudeLine(1, CLEAR_WRAPPER),
  claudeLine(2, GOAL),
  claudeLine(3, THINKING_ONLY),
  claudeLine(4, TOOL_CALL),
  claudeLine(5, TOOL_RESULT),
  claudeLine(6, ANSWER),
].join("\n");

function canonicalEvents() {
  return getSessionAdapter("claude").toCanonical(TRANSCRIPT, { nativeSessionId: "claude-semantics" }).events;
}

test("CLI control records never render as the user's words", () => {
  const events = canonicalEvents();
  const texts = events.map((event) => event.content.map((block) => block.text ?? "").join(""));
  for (const text of texts) {
    assert.ok(!text.includes("local-command-caveat"), `caveat leaked into a conversation event: ${text.slice(0, 80)}`);
    assert.ok(!text.includes("<command-name>"), `command wrapper leaked into a conversation event: ${text.slice(0, 80)}`);
  }
  const turns = transcriptTurns(events);
  const spoken = turns.filter((turn) => turn.kind === "user");
  assert.equal(spoken.length, 1);
  assert.match(spoken[0].text, /^\/goal 将 Avenic/);
  // `/goal` is the person's own line, not a CLI record: the command wrapper
  // rule must have kept it. Every other turn belongs to Claude.
  assert.deepEqual([...new Set(turns.map((turn) => turn.speaker))], ["You", "Claude"]);
});

test("a record that carries nothing to say does not become an empty turn", () => {
  const events = canonicalEvents();
  for (const event of events) {
    assert.ok(event.content.length > 0, `empty event survived: ${event.id}`);
  }
  const turns = transcriptTurns(events);
  for (const turn of turns) {
    assert.ok(turn.text || turn.tools.length > 0, `empty turn survived: ${turn.id}`);
  }
  // The thinking-only record produced no turn at all; the only agent words
  // are the answer (the tool turn carries the tool call, not words).
  assert.deepEqual(turns.filter((turn) => turn.text).map((turn) => turn.text), [
    "/goal 将 Avenic 的会话系统最终收敛为真正可靠、实时、无感的多 Agent 会话体验",
    "I'll start by reading the session module.",
  ]);
});

test("a tool result is the agent's machinery, folded under the agent's turn", () => {
  const events = canonicalEvents();
  const toolEvent = events.find((event) => event.content.some((block) => block.type === "tool_result"));
  assert.ok(toolEvent, "the tool result is still part of the conversation record");
  assert.equal(toolEvent.agent, "claude");
  assert.notEqual(toolEvent.role, "user");
  const turns = transcriptTurns(events);
  assert.deepEqual(turns.map((turn) => turn.speaker), ["You", "Claude", "Claude"]);
  const [callTurn] = turns.filter((turn) => turn.kind === "agent" && turn.tools.length > 0);
  assert.deepEqual(callTurn.tools.map((tool) => tool.kind), ["call", "result"]);
  assert.ok(!turns.some((turn) => turn.kind === "user" && turn.text.includes("export function session")));
});

test("the cross-agent projection keeps control records out and attributes tool traffic", () => {
  const events = canonicalEvents();
  const projection = buildProjection({
    session: { id: "claude-claude-semantics" },
    events,
    targetAgent: "codex",
    nativeSessionId: "codex-native-1",
    budget: 400_000,
  });
  assert.match(projection.checkpoint?.goal ?? projection.turns[0].text, /^\/goal 将 Avenic/);
  const requests = projection.checkpoint?.requests ?? [];
  for (const request of requests) {
    assert.ok(!request.includes("local-command-caveat"), "a control record became a user request");
    assert.ok(!request.includes("<command-name>"), "a command wrapper became a user request");
  }
  for (const turn of projection.turns.filter((item) => item.kind === "tool")) {
    assert.match(turn.text, /tool result|ran /);
  }
  const items = projectionItems(projection);
  for (const item of items) {
    const text = item.content.map((part) => part.text).join("");
    assert.ok(!text.includes("local-command-caveat"), "a control record reached the target as a message");
    if (text.includes("tool result")) {
      assert.notEqual(item.role, "user", "a tool result was handed over as the user's own words");
      assert.match(text, /Claude/, "a foreign tool result lost its agent attribution");
    }
  }
});

// ------------------------------------------------------- 盘上已经存着的那些 --
//
// 上面盯的是采集：这轮之后写进 store 的会话里没有控制记录。但项目里已经存着的
// 会话是旧版本写的，那时候它们被当作用户发言落在 events.jsonl 里（store 保留
// event 的全形，extensions 一起写回去）。读的人——会话视图、标题、跨 agent 投影、
// 交出去的 state——只能按同一条规则自己把它们认出来，否则升级只是换了新的写入
// 方式，用户看到的还是旧的那一版。

/** 一条旧版本存下来的 canonical event：形状和今天的 store 一样，内容还是旧的。 */
function storedEvent(index, role, text, record = {}) {
  return {
    id: `claude:claude-semantics:uuid-${index}`,
    agent: "claude",
    role,
    createdAt: AT(index),
    content: [{ type: "text", text }],
    model: null,
    provider: "anthropic",
    extensions: { claude: { record: { ...record, type: role, uuid: `uuid-${index}` }, message: { role, content: text } } },
  };
}

const WRAPPER_TEXT = "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>";
const META_TEXT = "Session title: Fix the resume catalog.";
// 一个人真的写了字的命令：信封里装着这个人的目标。
const WRAPPED_GOAL_TEXT = "<command-name>/goal</command-name>\n<command-message>goal</command-message>\n<command-args>Make the resume catalog visible to the CLI</command-args>";
const WRAPPED_GOAL = { type: "user", message: { role: "user", content: WRAPPED_GOAL_TEXT } };

/** 上一版留在盘上的东西：两枚控制记录、一句人说的话、一句回答。 */
function storedEvents() {
  return [
    storedEvent(0, "user", WRAPPER_TEXT),
    storedEvent(1, "user", META_TEXT, { isMeta: true }),
    storedEvent(2, "user", "Fix the resume catalog."),
    storedEvent(3, "assistant", "Starting with the catalog."),
  ];
}

test("a control record an older version stored is read as transport, not as a turn", () => {
  const events = storedEvents();
  const turns = transcriptTurns(events);
  const spoken = turns.filter((turn) => turn.kind === "user").map((turn) => turn.text);
  assert.deepEqual(spoken, ["Fix the resume catalog."], "读回来的存量里，只有人说的话是人的话");
  for (const turn of turns) {
    assert.ok(!turn.text.includes("<command-name>"), `command wrapper became a turn: ${turn.text.slice(0, 60)}`);
    assert.ok(!turn.text.includes(META_TEXT), `a meta record became a turn: ${turn.text.slice(0, 60)}`);
  }
  // 标题也读同一批事件：旧版存下的第一句是 `/model` 的信封，不是这个人说的第一句话。
  assert.equal(sessionSnippet(events), "Fix the resume catalog.");
});

test("the words a person put into a command are still their words", () => {
  const events = getSessionAdapter("claude")
    .toCanonical([claudeLine(0, WRAPPED_GOAL), claudeLine(1, ANSWER)].join("\n"), { nativeSessionId: "claude-wrapped" })
    .events;
  // `/goal …` 到盘上时穿着一身 CLI 的信封，但里面那一段是这个人写的——丢掉它
  // 就是把整整一个目标从会话里删掉。
  const turns = transcriptTurns(events);
  assert.deepEqual(turns.filter((turn) => turn.kind === "user").map((turn) => turn.text), ["Make the resume catalog visible to the CLI"]);
  // 信封本身不是人说的话：画出去的每一段里都不带着 CLI 的标记。
  for (const event of events) {
    for (const block of event.content) assert.ok(!String(block.text ?? "").includes("<command"), `a wrapper stayed on a stored event: ${String(block.text ?? "").slice(0, 60)}`);
  }
});

test("an older store's command records keep the person's words when they are read", () => {
  const events = [
    storedEvent(0, "user", WRAPPED_GOAL_TEXT),
    storedEvent(1, "assistant", "Starting with the catalog."),
  ];
  assert.deepEqual(transcriptTurns(events).filter((turn) => turn.kind === "user").map((turn) => turn.text), ["Make the resume catalog visible to the CLI"]);
  assert.equal(sessionSnippet(events), "Make the resume catalog visible to the CLI");
  assert.equal(deriveState(events).goal, "Make the resume catalog visible to the CLI");
  const handoff = buildHandoff({ session: { id: "claude-wrapped", project: { cwd: "C:\\fixture" } }, events, targetAgent: "codex" });
  assert.ok(handoff.markdown.includes("Make the resume catalog visible to the CLI"), "交出去的目标是这个人写的那句话");
  assert.ok(!handoff.markdown.includes("<command"), "交出去的东西里不带 CLI 的信封");
});

test("an OpenCode message's reasoning stays inside the model that thought it", () => {
  // 推理是模型内部的东西 —— 这条规则在 Claude 和 Codex 的读入里都写着，OpenCode 的
  // 读入不能是第二个分类器。推理进了存储，下一个 agent 读到的就是这些话。
  const canonical = getSessionAdapter("opencode").toCanonical({
    id: "ses_reasoning",
    messages: [
      {
        info: { id: "msg_1", role: "assistant", time: { created: Date.parse(AT(1)) } },
        parts: [{ type: "reasoning", text: "SECRET-INTERNAL-REASONING" }, { type: "text", text: "hi" }],
      },
      // 整条只有推理：没有可说的话，就没有这一条事件。
      { info: { id: "msg_2", role: "assistant", time: { created: Date.parse(AT(2)) } }, parts: [{ type: "reasoning", text: "more thinking" }] },
      // 什么都没有的一条：空的用户回合同样不是一句谁说的话。
      { info: { id: "msg_3", role: "user", time: { created: Date.parse(AT(3)) } }, parts: [] },
    ],
  });
  const texts = canonical.events.flatMap((event) => event.content).map((block) => String(block.text ?? ""));
  assert.ok(texts.some((text) => text.includes("hi")), "这个人真的看到的那句话还在");
  for (const text of texts) assert.ok(!text.includes("SECRET-INTERNAL-REASONING") && !text.includes("more thinking"), `推理进了存储：${text.slice(0, 40)}`);
  assert.deepEqual(canonical.events.map((event) => event.role), ["assistant"], "只有推理和空消息都不该变成事件");
});

test("a store an older version wrote with reasoning blocks does not hand them to the next agent", () => {
  // 已经发布过的版本把这些块写进过用户的存储：读的人也要挡住它们，否则改的只是新数据。
  const events = [
    {
      id: "opencode:ses_old:msg_1", agent: "opencode", role: "assistant", createdAt: AT(1),
      content: [{ type: "reasoning_summary", text: "SECRET-INTERNAL-REASONING" }, { type: "text", text: "the answer" }],
      model: null, provider: "opencode", extensions: {},
    },
  ];
  const turns = transcriptTurns(events);
  for (const turn of turns) assert.ok(!turn.text.includes("SECRET-INTERNAL-REASONING"), "推理不该被读成人话");
  const projection = buildProjection({ session: { id: "opencode-ses_old" }, events, targetAgent: "codex", nativeSessionId: "codex-native-2", budget: 400_000 });
  for (const turn of projection.turns) assert.ok(!turn.text.includes("SECRET-INTERNAL-REASONING"), "交给下一个 agent 的东西里没有别人的推理");
  const handoff = buildHandoff({ session: { id: "opencode-ses_old", project: { cwd: "/fixture" } }, events, targetAgent: "codex" });
  assert.ok(!handoff.markdown.includes("SECRET-INTERNAL-REASONING"));
});

test("the projection and the handoff read an older store by the same rule", () => {
  const events = storedEvents();
  const projection = buildProjection({
    session: { id: "claude-claude-semantics" },
    events,
    targetAgent: "codex",
    nativeSessionId: "codex-native-1",
    budget: 400_000,
  });
  // 这一小段历史装得下，所以目标就在第一个 turn 上；装不下的时候它落在 checkpoint 里
  // （上面那条用例走的是那条路）。
  assert.equal(projection.checkpoint?.goal ?? projection.turns[0].text, "Fix the resume catalog.");
  for (const turn of projection.turns) {
    assert.ok(!turn.text.includes("<command-name>"), `a wrapper reached the target: ${turn.text.slice(0, 60)}`);
    assert.ok(!turn.text.includes(META_TEXT), `a meta record reached the target: ${turn.text.slice(0, 60)}`);
  }
  const state = deriveState(events);
  assert.equal(state.goal, "Fix the resume catalog.", "交出去的 goal 不是 CLI 自己的记录");
  assert.equal(state.currentTask, "Fix the resume catalog.");
  const handoff = buildHandoff({ session: { id: "claude-claude-semantics", project: { cwd: "C:\\fixture" } }, events, targetAgent: "codex" });
  assert.ok(!handoff.markdown.includes("<command-name>"), "交出去的 markdown 里没有 CLI 的信封");
  assert.ok(!handoff.markdown.includes(META_TEXT), "交出去的 markdown 里没有 meta 记录");
});
